WDP190101-4 | Repair of buttons in product-box
Johny1010/WDP-1901-01 pull request #1
Opened 2019-02-01 14:12 UTC by Wyrafinowany

2019-02-01 15:55 UTC, Varenthein commented
Dodaj proszę opis pull requestu zgodnie z instrukcją z materiału.

> 1. Zakładając pull request, w tytule należy podać numer zadania z Jiry (w tym samym formacie, co nazwa brancha).
> 2. Jako opis podaj następujące informacje: opis problemu (co się dzieje, a co powinno się dziać) oraz opis działania rozwiązania.
> 3. pracujesz jeszcze nad zadaniem, ustaw mu label WIP, który jest skrótem od "Work In Progress".

2019-02-02 08:36 UTC, Wyrafinowany commented
Opis problemu:
Buttony "Quick view" oraz "Add to cart" powinny być widoczne tylko na hover całego boksa z produktem. Wtedy też powinno zmieniać się tło ceny. 

Opis rozwiazania:
Edycja klasy buttons oraz dodanie hover'a na klase product-box.

2019-02-02 11:43 UTC, Varenthein requested changes
Popraw proszę te dwie rzeczy.

2019-02-02 11:43 UTC, Varenthein commented on src/sass/components/_product-box.scss
> +
Po co ta linia przerwy?

2019-02-02 11:43 UTC, Varenthein commented on src/sass/components/_product-box.scss
>        display: flex;
Po co na hoverze ustawiać `display: flex` na `buttons`? `.buttons` domyslnie ma już taką wlasciwosc. W hoverze wystarczy zmienić `visibility`.

2019-02-02 11:52 UTC, Neonides commented on src/sass/components/_product-box.scss
>    .photo {
Odzielajmy klasy enterem. Utrzymujmy jedną konwencję projektu

2019-02-03 18:37 UTC, Varenthein approved these changes

2019-02-03 18:53 UTC, Neonides approved these changes

2019-02-04 14:13 UTC, merged