Wdp190101 24
Johny1010/WDP-1901-01 pull request #23
Opened 2019-02-19 15:32 UTC by Ciri1987

*Opis problemu*
Na stronie należy dodać sekcję "Promocje" według designu:
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-deals.png
Jest to zwykła statyczna sekcja (HTML i CSS). Wszystkie 3 boxy powinny być stałej wysokości - nawet, jeżeli użyje się większego zdjęcia w tle któregoś z nich, nie powinno ono wychodzić poza dany box, ani zmieniać jego rozmiaru.
*Rozwiązanie problemu*
- stworzenie w pliku html nowej sekcji "Deals" i podpięcie jej do index.html
- stworzenie stylów dla nowej sekcji
- dostosowanie boxów do wymagań klienta

2019-02-20 22:00 UTC, hul requested changes

2019-02-20 22:00 UTC, hul commented on src/partials/40_section-deals.html
> +<div class="section--deals">
Warto zachować spójne nazewnictwo: **section--deals** jest chyba jedym przykładem użycia **--**.

2019-02-20 22:00 UTC, hul commented on src/sass/components/_deals.scss
> +        margin-top: 15px;
W połączeniu z marginesem dolnym z *.deals-thumbnail-top* uzyskujemy dwa razy większy odstęp poziomy w prawej kolumnie niż między kolumnami - na mocku odstęp jest w obu przypadkach taki sam.

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +        h2 {
Nie stylujemy tagów htmlowych lepiej to zamienić na jakąś klasę. Jak zmienisz tag h2 na h3? to musisz zmieniać zarówno w htmlu jak css, a tak dodasz klasę do dowolnego html'a

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +            span {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +          h2 {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +            span {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +          h5 {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +          h3 {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +          h4 {
j.w

2019-02-21 07:10 UTC, Neonides commented on src/sass/components/_deals.scss
> +              span {
j.w

2019-02-22 10:01 UTC, Ciri1987 commented on src/partials/40_section-deals.html
> +<div class="section--deals">
Ok poprawione

2019-02-22 10:01 UTC, Ciri1987 commented on src/sass/components/_deals.scss
> +        margin-top: 15px;
Ok poprawione

2019-02-22 10:01 UTC, Ciri1987 commented on src/sass/components/_deals.scss
> +        h2 {
Ok poprawione

2019-02-26 07:25 UTC, Wyrafinowany commented
W mojej opinii przesunął bym napis w prawą stronę aby nie zakrywał krzesła --> https://ibb.co/L9qC409
oraz odsunął napis bardziej od krawędzi --> https://ibb.co/gmCfV0C
Poza tymi wymienionymi rzeczami, moim zdaniem jest wporządku

2019-02-27 07:32 UTC, Neonides approved these changes

2019-02-27 07:32 UTC, merged