WDP190101-6 | Add old price
Johny1010/WDP-1901-01 pull request #6
Opened 2019-02-04 15:43 UTC by Wyrafinowany

**Opis problemu:**
Na karcie produktu ma być możliwość dodania starej ceny, która ma być przekreślona. 
Tylko przy niektórych produktach będzie stara cena. 

*Opis rozwiazania:**
Dodanie nowych div'ów z starą ceną oraz styli w pliku product-box.scss.

2019-02-04 16:24 UTC, Varenthein requested changes
Dlaczego usuwasz też listę obok New Furniture?

2019-02-04 16:24 UTC, Varenthein commented
Dlaczego usuwasz też listę obok New Furniture?

2019-02-04 16:55 UTC, Wyrafinowany commented
Przez moja nieuwage to usunalem, juz poprawione.

2019-02-04 21:05 UTC, hul commented
Uwaga, ten PR zawiera zmiany https://github.com/Johny1010/WDP-1901-01/pull/3 :) Lepiej poczekać z mergem na https://github.com/Johny1010/WDP-1901-01/pull/3.

2019-02-05 12:19 UTC, Varenthein approved these changes

2019-02-06 20:15 UTC, hul approved these changes

2019-02-07 07:23 UTC, merged