WDP190101-14 | Add RWD to new furniture section
Johny1010/WDP-1901-01 pull request #9
Opened 2019-02-05 20:13 UTC by Wyrafinowany

**Opis problemu:**
Klient chciałby mieć w danych szerokościach odpowiednią ilość elementów w rzędzie:
> 1 element przy szerokości mniejszych niż +/- 568px
> 2 elementy przy szerokościach większych niż +/- 568px do 768px
> 3 elementy przy szerokościach większych niż +/- 768px do +/- 1200px
> 4 elemnty przy wyższych szerokościach

**Opis rozwiazania:**
Użycie odpowiednich klas z systemu grid. Ukrycie listy elementów przy szerokościach mniejszych niż 768px.

2019-02-05 22:26 UTC, Varenthein requested changes
Fajnie poradziłeś sobie ze zmianą układu, ale nie jestem pewien co do pomysłu ukrywania listy. Przecież ta lista ma swoją funkcjonalność. Przypuszczamy, że w zamysle klikniecie na element listy może np. służyc do zmiany widocznych produktów. Lepiej, żeby więc ona była wciąz widoczna moim zdaniem. Na pewno musi być jakoś zmieniona dla komórek, ale nie może być ukryta. Może po prostu umieścić ją niżej? Pod nagłowkiem "New furniture"?

2019-02-06 15:48 UTC, Wyrafinowany commented
Przemyślałem to i skorzystałem z Twojej podpowiedzi, umieściłem nią pod nagłówkiem. Dzięki!

2019-02-06 18:47 UTC, Varenthein approved these changes

2019-02-06 20:18 UTC, hul approved these changes

2019-02-06 20:51 UTC, merged